[program:quant-strategy-eth]
command=/home/admin/.pyenv/versions/3.10.0/bin/python3 -u strategies/rsi_1min_strategy.py
directory=/home/admin/.openclaw/workspace/quant/v3-architecture
user=admin
group=admin
autostart=true
autorestart=true
startretries=10
retrywait=5
stderr_logfile=/home/admin/.openclaw/workspace/quant/v3-architecture/logs/supervisor_eth_err.log
stdout_logfile=/home/admin/.openclaw/workspace/quant/v3-architecture/logs/supervisor_eth_out.log
environment=PYTHONPATH="/home/admin/.openclaw/workspace/quant/v3-architecture"
numprocs=1
process_name=%(program_name)s
startsecs=5
stopwaitsecs=10
stopsignal=TERM

[program:quant-strategy-link]
command=/home/admin/.pyenv/versions/3.10.0/bin/python3 -u strategies/link_rsi_detailed_strategy.py
directory=/home/admin/.openclaw/workspace/quant/v3-architecture
user=admin
group=admin
autostart=true
autorestart=true
startretries=10
retrywait=5
stderr_logfile=/home/admin/.openclaw/workspace/quant/v3-architecture/logs/supervisor_link_err.log
stdout_logfile=/home/admin/.openclaw/workspace/quant/v3-architecture/logs/supervisor_link_out.log
environment=PYTHONPATH="/home/admin/.openclaw/workspace/quant/v3-architecture"
numprocs=1
process_name=%(program_name)s
startsecs=5
stopwaitsecs=10
stopsignal=TERM

[program:quant-strategy-avax]
command=/home/admin/.pyenv/versions/3.10.0/bin/python3 -u strategies/rsi_scale_in_strategy.py
directory=/home/admin/.openclaw/workspace/quant/v3-architecture
user=admin
group=admin
autostart=true
autorestart=true
startretries=10
retrywait=5
stderr_logfile=/home/admin/.openclaw/workspace/quant/v3-architecture/logs/supervisor_avax_err.log
stdout_logfile=/home/admin/.openclaw/workspace/quant/v3-architecture/logs/supervisor_avax_out.log
environment=PYTHONPATH="/home/admin/.openclaw/workspace/quant/v3-architecture"
numprocs=1
process_name=%(program_name)s
startsecs=5
stopwaitsecs=10
stopsignal=TERM
